// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Checked-in exact allowlist for the package-wide `lint/performance/noAwaitInLoops`
 * policy.
 *
 * Two-layer design. biome.jsonc deliberately keeps `noAwaitInLoops: "off"`
 * for `src/`, `bin/`, `bench/`, `connectors/` (its own comment explains why:
 * the package's dominant loop shapes are genuinely sequential) — that
 * override is NOT removed by this file and stays in effect for ordinary
 * `pnpm check`/`biome check` runs. This file is the independent second
 * layer: the sole sanctioned exception mechanism, checked by a dedicated
 * gate that re-enables the rule out-of-band. Every (path, line, column)
 * below is a specific, reviewed, genuinely intentional sequential await,
 * not an escape hatch.
 *
 * Enforcement: `scripts/check-no-await-in-loops-conformance.ts` (wired into
 * `pnpm verify` as `check:noAwaitInLoops-conformance`) re-runs Biome with
 * the rule forced back to "error" for its own invocation only and fails
 * the build on:
 *   1. any LIVE finding whose location is not listed here (a new sequential
 *      await was introduced and was never reviewed/categorized), and
 *   2. any LISTED row whose location Biome no longer flags (the code moved or
 *      changed shape — the exception is stale and must be re-reviewed, not
 *      silently carried forward).
 *
 * Every row is categorized by WHY it must stay sequential — never a generic
 * blanket rationale:
 *
 *   - ordered_browser_interaction: sequential Playwright action against the shared page/context
 *   - dependent_pagination: next request depends on the prior page's cursor/offset/response
 *   - bounded_retry_polling: retry/backoff/poll loop gated on the prior attempt's outcome
 *   - provider_pacing_backpressure: rate-limited/budget-gated external call
 *   - ordered_protocol_emission: Collection Profile protocol emission requiring in-order delivery
 *   - dependent_file_cursor: sequential file/dir walk, incremental byte-offset read, or one-way fs mutation
 *   - shared_mutable_accumulator: loop body mutates a shared accumulator the next iteration reads
 *   - test_assertion_sequencing: test drives/asserts an ordered per-case side effect
 *   - devtool_sequential_output: manual dev-tool script printing ordered per-item console output
 *
 * To add a new entry after a genuine, reviewed addition: run
 *   pnpm exec biome check --only=performance/noAwaitInLoops --max-diagnostics=1000 \
 *     --reporter=json . (with the rule flipped to "error" in a scratch biome.jsonc
 *   copy, or use scripts/check-no-await-in-loops-conformance.ts --dump-live to print
 *   the current live finding set) — then classify ONLY the new row(s) into the
 *   right category above and append them here. Do not regenerate the whole file.
 */

export type NoAwaitInLoopsReasonCategory =
	| "ordered_browser_interaction"
	| "dependent_pagination"
	| "bounded_retry_polling"
	| "provider_pacing_backpressure"
	| "ordered_protocol_emission"
	| "dependent_file_cursor"
	| "shared_mutable_accumulator"
	| "test_assertion_sequencing"
	| "devtool_sequential_output";

export interface NoAwaitInLoopsAllowlistEntry {
	readonly category: NoAwaitInLoopsReasonCategory;
	readonly column: number;
	readonly line: number;
	/** Short, site-specific note — the awaited call this row covers. */
	readonly note: string;
	readonly path: string;
}

export const NO_AWAIT_IN_LOOPS_ALLOWLIST: readonly NoAwaitInLoopsAllowlistEntry[] =
	[
		{
			path: "bench/claude-code-two-pass.ts",
			line: 239,
			column: 13,
			category: "devtool_sequential_output",
			note: "runLegacyBaseline(): manual dev-tool script printing ordered per-item console output",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 306,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 422,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 546,
			column: 10,
			category: "dependent_file_cursor",
			note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 627,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 708,
			column: 3,
			category: "dependent_file_cursor",
			note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 742,
			column: 3,
			category: "dependent_file_cursor",
			note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 781,
			column: 3,
			category: "dependent_file_cursor",
			note: "processSessionDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 822,
			column: 3,
			category: "dependent_file_cursor",
			note: "scanProjectDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bin/amazon-privacy-probe.ts",
			line: 42,
			column: 4,
			category: "ordered_browser_interaction",
			note: "page.goto(): sequential Playwright action against the shared page/context",
		},
		{
			path: "bin/register-all.ts",
			line: 77,
			column: 4,
			category: "devtool_sequential_output",
			note: "registerManifest(): manual dev-tool script printing ordered per-item console output",
		},
		{
			path: "bin/replay-pilot-fixtures.ts",
			line: 162,
			column: 13,
			category: "dependent_pagination",
			note: "replayConnector(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "bin/replay-schemas.ts",
			line: 263,
			column: 18,
			category: "dependent_pagination",
			note: "replayConnector(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "bin/scrub-fixtures.ts",
			line: 62,
			column: 17,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bin/scrub-fixtures.ts",
			line: 172,
			column: 17,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bin/scrub-fixtures.ts",
			line: 182,
			column: 16,
			category: "dependent_file_cursor",
			note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bin/scrub-fixtures.ts",
			line: 189,
			column: 4,
			category: "dependent_file_cursor",
			note: "mkdir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 894,
			column: 18,
			category: "ordered_browser_interaction",
			note: "resolveOrderDetail(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 904,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 949,
			column: 18,
			category: "ordered_browser_interaction",
			note: "recoverPendingOrderItemDetailGapPage(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1165,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1189,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1663,
			column: 3,
			category: "dependent_pagination",
			note: "deps.progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1688,
			column: 4,
			category: "dependent_pagination",
			note: "deps.progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1910,
			column: 6,
			category: "dependent_pagination",
			note: "progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1966,
			column: 6,
			category: "dependent_pagination",
			note: "progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/amazon/integration.test.ts",
			line: 452,
			column: 19,
			category: "test_assertion_sequencing",
			note: "processListOrder(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/apple_photos/index.ts",
			line: 188,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_health/index.ts",
			line: 77,
			column: 5,
			category: "ordered_protocol_emission",
			note: "onRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 1617,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 1818,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 1872,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 2005,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emit(): statement DETAIL_GAP emissions preserve source outcome order",
		},
		{
			path: "connectors/chase/index.ts",
			line: 2548,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 2580,
			column: 19,
			category: "ordered_browser_interaction",
			note: "processAccountDownload(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/chase/index.ts",
			line: 2900,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 1318,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2138,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2303,
			column: 3,
			category: "dependent_pagination",
			note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2580,
			column: 15,
			category: "ordered_protocol_emission",
			note: "emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2603,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2699,
			column: 4,
			category: "dependent_pagination",
			note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2734,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2837,
			column: 4,
			category: "dependent_pagination",
			note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 3170,
			column: 16,
			category: "provider_pacing_backpressure",
			note: "fetchChatGptPressureProbeStatus(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 3901,
			column: 15,
			category: "provider_pacing_backpressure",
			note: "fetchBatch(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 3937,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 3974,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4003,
			column: 6,
			category: "ordered_protocol_emission",
			note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4226,
			column: 12,
			category: "provider_pacing_backpressure",
			note: "fetchConversationDetailWaitingOutCircuit(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4316,
			column: 12,
			category: "dependent_pagination",
			note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4489,
			column: 18,
			category: "provider_pacing_backpressure",
			note: "recoverPendingConversationDetailGapPage(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4644,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4877,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitConversation(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/integration.test.ts",
			line: 5119,
			column: 3,
			category: "test_assertion_sequencing",
			note: "runConversationsAndMessagesStreams(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 428,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 556,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 595,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 756,
			column: 10,
			category: "dependent_file_cursor",
			note: "readBoundedUtf8(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 857,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 918,
			column: 10,
			category: "dependent_file_cursor",
			note: "readBoundedUtf8(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1016,
			column: 3,
			category: "dependent_file_cursor",
			note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1048,
			column: 4,
			category: "dependent_file_cursor",
			note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1105,
			column: 3,
			category: "dependent_file_cursor",
			note: "processSessionDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1146,
			column: 3,
			category: "dependent_file_cursor",
			note: "scanProjectDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1450,
			column: 14,
			category: "dependent_file_cursor",
			note: "readdir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1633,
			column: 4,
			category: "ordered_protocol_emission",
			note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1705,
			column: 3,
			category: "ordered_protocol_emission",
			note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1796,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitDerivedCoverage(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1815,
			column: 4,
			category: "ordered_protocol_emission",
			note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1845,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitGatedInventoryStream(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 2194,
			column: 23,
			category: "dependent_file_cursor",
			note: "scanSessionSource(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 2222,
			column: 24,
			category: "dependent_file_cursor",
			note: "scanSessionSource(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 2320,
			column: 21,
			category: "dependent_file_cursor",
			note: "scanChildSource(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/integration.test.ts",
			line: 88,
			column: 3,
			category: "test_assertion_sequencing",
			note: "processJsonlLine(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/claude_code/local-jsonl-incremental.test.ts",
			line: 501,
			column: 5,
			category: "test_assertion_sequencing",
			note: "import(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/claude_code/local-jsonl-incremental.test.ts",
			line: 1040,
			column: 18,
			category: "test_assertion_sequencing",
			note: "makeAttachmentSource(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/codex/index.ts",
			line: 588,
			column: 18,
			category: "dependent_file_cursor",
			note: "statAndRead(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/codex/index.ts",
			line: 604,
			column: 4,
			category: "ordered_protocol_emission",
			note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/index.ts",
			line: 623,
			column: 18,
			category: "dependent_file_cursor",
			note: "statAndRead(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/codex/index.ts",
			line: 672,
			column: 9,
			category: "dependent_file_cursor",
			note: "isDirectoryPath(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/codex/index.ts",
			line: 1610,
			column: 31,
			category: "shared_mutable_accumulator",
			note: "scanRollouts(): sequential (not Promise.all) existence check over args.roots — a short, fixed list (today: the primary and archive roots) pushed into a single shared rootChecks accumulator; also keeps the codex file clear of the local-source-bounded-file-read.test.ts .all()-pattern guard, which flags Promise.all as a false positive on the SQLite-unbounded-read pattern it actually polices.",
		},
		{
			path: "connectors/codex/index.ts",
			line: 1643,
			column: 4,
			category: "shared_mutable_accumulator",
			note: "scanRollouts(): the merged sessions/ + sessions-archive/ root walk shares seenCursorKeysThisScan, newFileCursors, newMtimes, and running counters across both roots' walks (see ARCHIVAL-CONTRACT.md); processRolloutEntry mutates them, so the two roots cannot be walked in parallel without a data race on that shared state.",
		},
		{
			path: "connectors/codex/index.ts",
			line: 2130,
			column: 3,
			category: "ordered_protocol_emission",
			note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/index.ts",
			line: 2189,
			column: 4,
			category: "ordered_protocol_emission",
			note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/index.ts",
			line: 2252,
			column: 19,
			category: "ordered_protocol_emission",
			note: "resolveGatedInventoryRecords(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/index.ts",
			line: 2369,
			column: 3,
			category: "ordered_protocol_emission",
			note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/rollout-stream.test.ts",
			line: 266,
			column: 4,
			category: "test_assertion_sequencing",
			note: "once(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/github/index.ts",
			line: 437,
			column: 3,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 467,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 561,
			column: 3,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 589,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 676,
			column: 3,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 708,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 977,
			column: 16,
			category: "ordered_protocol_emission",
			note: "emitPullRequestItem(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 1017,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 1120,
			column: 18,
			category: "dependent_pagination",
			note: "drainPrSearchWindow(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 1242,
			column: 3,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 1265,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 631,
			column: 21,
			category: "ordered_protocol_emission",
			note: "deps.hydrateAttachment(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 652,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitProtocol(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 676,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 778,
			column: 4,
			category: "ordered_protocol_emission",
			note: "uploadBodyBlob(): canonical field bytes must bind before their record is emitted",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 836,
			column: 22,
			category: "ordered_protocol_emission",
			note: "processMessage(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 1122,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 2145,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitProtocol(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 2376,
			column: 16,
			category: "provider_pacing_backpressure",
			note: "processServedAttachmentRecoveryGap(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 3425,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 3657,
			column: 23,
			category: "shared_mutable_accumulator",
			note: "runThreadsPass(): each range updates the shared fingerprint cursor and accumulated coverage count",
		},
		{
			path: "connectors/google_messages/index.ts",
			line: 732,
			column: 14,
			category: "dependent_pagination",
			note: "fetchChatMessages(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_messages/index.ts",
			line: 869,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_maps/archive-stream.test.ts",
			line: 200,
			column: 4,
			category: "dependent_file_cursor",
			note: "large-path oracle writes one ordered JSON array to a shared stream",
		},
		{
			path: "connectors/google_maps/archive-stream.ts",
			line: 793,
			column: 4,
			category: "ordered_protocol_emission",
			note: "drain(): sequential event callbacks preserve source order and backpressure",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 141,
			column: 3,
			category: "dependent_file_cursor",
			note: "walkDiscoveryDirectory(): sequential file/dir walk follows the discovered source boundary",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 174,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRequestedSkip(): ordered SKIP_RESULT protocol emission",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 292,
			column: 9,
			category: "ordered_protocol_emission",
			note: "processPointRecords(): ordered schema admission and point protocol emission",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 347,
			column: 9,
			category: "ordered_protocol_emission",
			note: "processSegmentRecords(): ordered schema admission and segment protocol emission",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 495,
			column: 3,
			category: "dependent_file_cursor",
			note: "loadExports(): sequential file progress follows the discovered source order",
		},
		{
			path: "connectors/google_maps_data_portability/index.ts",
			line: 310,
			column: 18,
			category: "dependent_pagination",
			note: "collectResourceGroup(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 122,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 178,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 229,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 339,
			column: 18,
			category: "dependent_file_cursor",
			note: "buildPhotoRecordForFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 543,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/heb/index.ts",
			line: 315,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/heb/index.ts",
			line: 713,
			column: 18,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/heb/index.ts",
			line: 738,
			column: 5,
			category: "ordered_browser_interaction",
			note: "recoverPendingOrderItemDetailGapPage(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/heb/index.ts",
			line: 786,
			column: 18,
			category: "ordered_browser_interaction",
			note: "resolveOrderDetail(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/heb/index.ts",
			line: 858,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/heb/index.ts",
			line: 988,
			column: 20,
			category: "ordered_browser_interaction",
			note: "loadListPage(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/heb/index.ts",
			line: 1022,
			column: 4,
			category: "ordered_browser_interaction",
			note: "processListOrder(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/ical/index.ts",
			line: 61,
			column: 11,
			category: "dependent_file_cursor",
			note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/ical/index.ts",
			line: 81,
			column: 17,
			category: "ordered_protocol_emission",
			note: "fetchIcs(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ical/index.ts",
			line: 126,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ical/index.ts",
			line: 160,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitEventsFromSource(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/imessage/index.ts",
			line: 370,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/imessage/index.ts",
			line: 417,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/imessage/index.ts",
			line: 694,
			column: 18,
			category: "provider_pacing_backpressure",
			note: "resolveAttachmentHydration(): rate-limited/budget-gated blob-upload call",
		},
		{
			path: "connectors/notion/index.ts",
			line: 216,
			column: 3,
			category: "dependent_pagination",
			note: "progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/notion/index.ts",
			line: 303,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/oura/index.ts",
			line: 161,
			column: 16,
			category: "dependent_pagination",
			note: "oura(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/oura/index.ts",
			line: 260,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/pocket/index.ts",
			line: 182,
			column: 18,
			category: "dependent_pagination",
			note: "fetchPocketPage(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/pocket/index.ts",
			line: 191,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/reddit/index.ts",
			line: 323,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/reddit/index.ts",
			line: 465,
			column: 3,
			category: "dependent_pagination",
			note: "collectStream(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/reddit/index.ts",
			line: 622,
			column: 18,
			category: "dependent_pagination",
			note: "progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/reddit/integration.test.ts",
			line: 1297,
			column: 3,
			category: "test_assertion_sequencing",
			note: "collectStream(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/reddit/integration.test.ts",
			line: 1360,
			column: 3,
			category: "test_assertion_sequencing",
			note: "collectStream(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/slack/index.ts",
			line: 1410,
			column: 18,
			category: "shared_mutable_accumulator",
			note: "refreshScopedArchive(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "connectors/slack/index.ts",
			line: 1545,
			column: 5,
			category: "shared_mutable_accumulator",
			note: "runRequestedStreams(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "connectors/slack/index.ts",
			line: 1818,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 1822,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 1827,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 1929,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2057,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitWithFingerprint(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2124,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitWithFingerprint(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2534,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2562,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2574,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2586,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2631,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 3080,
			column: 28,
			category: "dependent_file_cursor",
			note: "reclaimUploads(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/slack/slack-api.ts",
			line: 298,
			column: 16,
			category: "dependent_pagination",
			note: "slackApiPost(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/slack/slack-api.ts",
			line: 366,
			column: 16,
			category: "dependent_pagination",
			note: "slackApiGet(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/spotify/index.ts",
			line: 316,
			column: 3,
			category: "dependent_pagination",
			note: "paginate(): page progress follows the fetched page before advancing its cursor",
		},
		{
			path: "connectors/spotify/index.ts",
			line: 321,
			column: 18,
			category: "shared_mutable_accumulator",
			note: "paginate(): fold accumulator from each item is the next iteration's input",
		},
		{
			path: "connectors/spotify/index.ts",
			line: 481,
			column: 3,
			category: "ordered_protocol_emission",
			note: "progress(): top-artist time-range windows report in-order before the next window starts",
		},
		{
			path: "connectors/strava/index.ts",
			line: 194,
			column: 4,
			category: "dependent_pagination",
			note: "progressWithSignals(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/strava/index.ts",
			line: 216,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/twitter_archive/index.ts",
			line: 150,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/credit-card-billing-stats.test.ts",
			line: 256,
			column: 3,
			category: "test_assertion_sequencing",
			note: "deps.emitRecord(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 352,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 512,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 847,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 912,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 1263,
			column: 4,
			category: "ordered_browser_interaction",
			note: "page.goto(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2085,
			column: 19,
			category: "bounded_retry_polling",
			note: "runSingleLadderAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2227,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2365,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2598,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2818,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2858,
			column: 3,
			category: "ordered_protocol_emission",
			note: "processPdfStatementRow(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 3066,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 3350,
			column: 20,
			category: "ordered_browser_interaction",
			note: "navigateToCardOrGap(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 3380,
			column: 6,
			category: "ordered_protocol_emission",
			note: "emitCreditCardNavFailureGaps(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/integration.test.ts",
			line: 822,
			column: 19,
			category: "test_assertion_sequencing",
			note: "driveExport(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/usaa/statement-pdfs.ts",
			line: 202,
			column: 7,
			category: "ordered_browser_interaction",
			note: "c.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/statement-pdfs.ts",
			line: 230,
			column: 7,
			category: "ordered_browser_interaction",
			note: "c.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/statement-pdfs.ts",
			line: 681,
			column: 3,
			category: "ordered_browser_interaction",
			note: "hydrateOneStatement(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/transactions-coverage.test.ts",
			line: 225,
			column: 4,
			category: "test_assertion_sequencing",
			note: "deps.emit(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/venmo/index.ts",
			line: 273,
			column: 3,
			category: "dependent_pagination",
			note: "progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/venmo/index.ts",
			line: 329,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/venmo/index.ts",
			line: 364,
			column: 3,
			category: "dependent_pagination",
			note: "progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/venmo/index.ts",
			line: 461,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/whatsapp/chat-identity-reconciliation.test.ts",
			line: 246,
			column: 23,
			category: "test_assertion_sequencing",
			note: "runImport(): test drives/asserts an ordered per-case side effect (each run's STATE cursor is threaded into the next run to prove the per-identityKey alias cap accumulates and plateaus correctly across 25 sequential imports)",
		},
		{
			path: "connectors/whatsapp/index.ts",
			line: 174,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/whatsapp/index.ts",
			line: 831,
			column: 18,
			category: "provider_pacing_backpressure",
			note: "buildAttachmentRecord(): rate-limited/budget-gated blob-upload call (wraps uploadBlob())",
		},
		{
			path: "connectors/whatsapp/index.ts",
			line: 1260,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitStateForCursor(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/whatsapp/index.ts",
			line: 1334,
			column: 36,
			category: "dependent_file_cursor",
			note: "parseExportFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 277,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): sleep records must preserve source and protocol order",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 282,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): workout records must preserve source and protocol order",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 329,
			column: 25,
			category: "provider_pacing_backpressure",
			note: "fetchPath(): bounded WHOOP history windows stay sequential to avoid provider pressure",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 332,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitAggregateRecord(): records preserve WHOOP window order before cursor state",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 339,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emit(): stream cursor state follows all covered WHOOP records",
		},
		{
			path: "connectors/whatsapp/txt-toctou.test.ts",
			line: 48,
			column: 4,
			category: "test_assertion_sequencing",
			note: "waitForBarrier(): test waits for the fixture writer's ordered filesystem barrier",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1030,
			column: 5,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1279,
			column: 4,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1285,
			column: 5,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1388,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1510,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1644,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1769,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1886,
			column: 4,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 2022,
			column: 3,
			category: "dependent_pagination",
			note: "progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 2042,
			column: 4,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 2184,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 2486,
			column: 17,
			category: "dependent_pagination",
			note: "collectForBudget(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "src/adaptive-lane.ts",
			line: 495,
			column: 20,
			category: "bounded_retry_polling",
			note: "runAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/amazon.ts",
			line: 71,
			column: 13,
			category: "ordered_browser_interaction",
			note: "locator.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/amazon.ts",
			line: 74,
			column: 8,
			category: "ordered_browser_interaction",
			note: "el.isVisible(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/chatgpt.ts",
			line: 393,
			column: 4,
			category: "ordered_browser_interaction",
			note: "candidate.waitFor(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/chatgpt.ts",
			line: 603,
			column: 3,
			category: "bounded_retry_polling",
			note: "checkpoint(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/chatgpt.ts",
			line: 996,
			column: 3,
			category: "bounded_retry_polling",
			note: "page.waitForTimeout(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/heb.test.ts",
			line: 1037,
			column: 4,
			category: "test_assertion_sequencing",
			note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/heb.test.ts",
			line: 1086,
			column: 4,
			category: "test_assertion_sequencing",
			note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/heb.test.ts",
			line: 1156,
			column: 4,
			category: "test_assertion_sequencing",
			note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/heb.test.ts",
			line: 1191,
			column: 14,
			category: "test_assertion_sequencing",
			note: "ensureHebSession(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 85,
			column: 30,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 104,
			column: 17,
			category: "ordered_browser_interaction",
			note: "locator.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 107,
			column: 31,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 128,
			column: 17,
			category: "ordered_browser_interaction",
			note: "locator.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 131,
			column: 31,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 157,
			column: 30,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 201,
			column: 30,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 353,
			column: 19,
			category: "ordered_browser_interaction",
			note: "inspectPostSubmitAuthSurface(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 507,
			column: 18,
			category: "ordered_browser_interaction",
			note: "fillWhenUsable(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 529,
			column: 37,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 744,
			column: 20,
			category: "bounded_retry_polling",
			note: "waitForUniqueVerificationCodeFormRoot(): retry/poll until the remounted OTP surface is uniquely actionable",
		},
		{
			path: "src/auto-login/manual-action-copy.test.ts",
			line: 48,
			column: 15,
			category: "test_assertion_sequencing",
			note: "readFile(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/reddit.test.ts",
			line: 132,
			column: 5,
			category: "bounded_retry_polling",
			note: "makeLocator().waitFor(): bounded test double polling until the simulated locator attaches",
		},
		{
			path: "src/auto-login/reddit.ts",
			line: 326,
			column: 8,
			category: "bounded_retry_polling",
			note: "hasSessionCookie(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/usaa.ts",
			line: 173,
			column: 17,
			category: "ordered_browser_interaction",
			note: "action.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/usaa.ts",
			line: 178,
			column: 14,
			category: "ordered_browser_interaction",
			note: "locator.isVisible(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/usaa.ts",
			line: 333,
			column: 16,
			category: "bounded_retry_polling",
			note: "requestOtp(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/browser-launch.ts",
			line: 542,
			column: 11,
			category: "bounded_retry_polling",
			note: "runAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/browser-launch.ts",
			line: 1002,
			column: 21,
			category: "dependent_file_cursor",
			note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/browser-launch.ts",
			line: 1112,
			column: 14,
			category: "shared_mutable_accumulator",
			note: "closeRemoteDevToolsTarget(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/browser-launch.ts",
			line: 1125,
			column: 25,
			category: "shared_mutable_accumulator",
			note: "fetchRemoteDevToolsTargets(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/collector-registry.test.ts",
			line: 72,
			column: 31,
			category: "test_assertion_sequencing",
			note: "readFile(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/collector-registry.test.ts",
			line: 91,
			column: 31,
			category: "test_assertion_sequencing",
			note: "readFile(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-http-governor.test.ts",
			line: 330,
			column: 3,
			category: "test_assertion_sequencing",
			note: "g.request(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-http-governor.test.ts",
			line: 359,
			column: 3,
			category: "test_assertion_sequencing",
			note: "g.request(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-http-governor.test.ts",
			line: 423,
			column: 3,
			category: "test_assertion_sequencing",
			note: "g1.request(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-runtime-session-watchdog.test.ts",
			line: 159,
			column: 4,
			category: "test_assertion_sequencing",
			note: "watchdog.checkpoint(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-runtime.ts",
			line: 1672,
			column: 7,
			category: "shared_mutable_accumulator",
			note: "closeBrowserPage(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/interaction-handler.ts",
			line: 87,
			column: 4,
			category: "dependent_file_cursor",
			note: "access(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/interaction-handler.ts",
			line: 126,
			column: 18,
			category: "bounded_retry_polling",
			note: "promptStdin(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/local-device-runtime.ts",
			line: 303,
			column: 3,
			category: "shared_mutable_accumulator",
			note: "queue.enqueue(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/local-device-runtime.ts",
			line: 393,
			column: 16,
			category: "shared_mutable_accumulator",
			note: "input.queue.dequeueReady(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/local-jsonl-cursor.ts",
			line: 94,
			column: 25,
			category: "dependent_file_cursor",
			note: "handle.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/local-jsonl-cursor.ts",
			line: 229,
			column: 26,
			category: "dependent_file_cursor",
			note: "handle.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/local-jsonl-cursor.ts",
			line: 248,
			column: 5,
			category: "dependent_file_cursor",
			note: "onLine(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/profile-lock.ts",
			line: 141,
			column: 4,
			category: "dependent_file_cursor",
			note: "fs.unlink(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/reference-blob-uploader.test.ts",
			line: 47,
			column: 11,
			category: "test_assertion_sequencing",
			note: "reader.read(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/reference-blob-uploader.test.ts",
			line: 118,
			column: 3,
			category: "test_assertion_sequencing",
			note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/scheduler-runner.ts",
			line: 287,
			column: 4,
			category: "devtool_sequential_output",
			note: "registerManifest(): manual dev-tool script printing ordered per-item console output",
		},
		{
			path: "connectors/apple_contacts/bounded-response-read.ts",
			line: 93,
			column: 28,
			category: "dependent_file_cursor",
			note: "reader.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/apple_contacts/carddav-client.ts",
			line: 79,
			column: 39,
			category: "dependent_pagination",
			note: "davRequest(): next redirect hop depends on the prior response's Location header",
		},
		{
			path: "connectors/apple_contacts/discovery.ts",
			line: 271,
			column: 15,
			category: "dependent_pagination",
			note: "propfindFollowingRedirects(): next redirect hop depends on the prior response's Location header",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 400,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 548,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitContactRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 552,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 575,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitContactRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 755,
			column: 9,
			category: "shared_mutable_accumulator",
			note: "collectAddressBook(): loop body mutates a shared bookCursor/newState accumulator the next iteration reads",
		},
		{
			path: "connectors/google_calendar/api.ts",
			line: 226,
			column: 26,
			category: "dependent_pagination",
			note: "listCalendars(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_calendar/index.ts",
			line: 177,
			column: 16,
			category: "dependent_pagination",
			note: "pageThroughEvents(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_calendar/index.ts",
			line: 193,
			column: 5,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_calendar/index.ts",
			line: 302,
			column: 5,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_calendar/index.ts",
			line: 328,
			column: 3,
			category: "shared_mutable_accumulator",
			note: "collectGoogleCalendar(): loop body mutates a shared nextEventsState accumulator the next iteration reads",
		},
		{
			path: "connectors/google_contacts/api.ts",
			line: 303,
			column: 26,
			category: "dependent_pagination",
			note: "listContactGroups(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_contacts/index.ts",
			line: 193,
			column: 16,
			category: "dependent_pagination",
			note: "syncPeoplePages(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_contacts/index.ts",
			line: 212,
			column: 5,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_contacts/index.ts",
			line: 309,
			column: 5,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 296,
			column: 27,
			category: "dependent_file_cursor",
			note: "reader.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 754,
			column: 4,
			category: "provider_pacing_backpressure",
			note: "normalizeOneAttachment(): rate-limited/budget-gated blob-upload call",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 920,
			column: 3,
			category: "dependent_pagination",
			note: "fetchPaginatedList(): next request depends on the prior page's page-number cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1349,
			column: 18,
			category: "provider_pacing_backpressure",
			note: "emitInScopeGroupMessages(): toGroupMessageRecord() rate-limited/budget-gated blob-upload call",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1410,
			column: 3,
			category: "dependent_pagination",
			note: "collectGroupMessagesForwardFromCursor(): next request depends on the prior page's after_id cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1547,
			column: 3,
			category: "dependent_pagination",
			note: "collectGroupMessagesBackwardToNaturalEnd(): next request depends on the prior page's before_id cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1858,
			column: 6,
			category: "ordered_protocol_emission",
			note: 'emitRecord("groups"): Collection Profile protocol emission requiring in-order delivery',
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1894,
			column: 6,
			category: "ordered_protocol_emission",
			note: 'emitRecord("direct_messages"): Collection Profile protocol emission requiring in-order delivery',
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1963,
			column: 3,
			category: "dependent_pagination",
			note: "collectDirectChatMessagesForChat(): next request depends on the prior page's before_id cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1995,
			column: 19,
			category: "provider_pacing_backpressure",
			note: "toDirectChatMessageRecord(): rate-limited/budget-gated blob-upload call",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 2047,
			column: 24,
			category: "shared_mutable_accumulator",
			note: "collectDirectChatMessages(): loop body mutates a shared considered accumulator the next iteration reads",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 2175,
			column: 25,
			category: "shared_mutable_accumulator",
			note: "collectGroupMessages(): loop body mutates shared considered/nextCursors accumulators the next iteration reads",
		},
		{
			path: "connectors/groupme/incremental-frontier.test.ts",
			line: 542,
			column: 16,
			category: "test_assertion_sequencing",
			note: "cappedForwardWalk(): deliberately reimplements a page-capped pagination loop to prove the >old-cap discriminator test actually fails under the old (removed) cap — sequential by design, not production code",
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 215,
			column: 28,
			category: "dependent_file_cursor",
			note: "readBodyWithStreamingCap(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 879,
			column: 4,
			category: "ordered_protocol_emission",
			note: 'emitRecord("libraries"): Collection Profile protocol emission requiring in-order delivery',
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 926,
			column: 21,
			category: "dependent_pagination",
			note: "collectItemsForLibrary(): next request depends on the prior page's StartIndex cursor",
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 968,
			column: 4,
			category: "ordered_protocol_emission",
			note: 'emitRecord("items"): Collection Profile protocol emission requiring in-order delivery',
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 1008,
			column: 3,
			category: "shared_mutable_accumulator",
			note: "collectItems(): loop body mutates shared state.items/totalItemsEmitted accumulator the next iteration reads",
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 1084,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitErrorSkipResults(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/netflix_export/index.ts",
			line: 356,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/netflix_export/parsers.ts",
			line: 187,
			column: 26,
			category: "dependent_file_cursor",
			note: "fd.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/steam/index.ts",
			line: 482,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "src/auto-login/venmo.test.ts",
			line: 898,
			column: 5,
			category: "test_assertion_sequencing",
			note: "ensureVenmoSession(): test drives an ordered retry-if-retryable dispatch simulation",
		},
		{
			path: "scripts/run-tests.mjs",
			line: 32,
			column: 2,
			category: "dependent_file_cursor",
			note: "collectTestFiles(): sequential glob() per fixed test-directory pattern; trivial fixed-size loop over 3 patterns, no reason to parallelize",
		},
	];
