// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

// Post-login challenge handling in the legacy instagram-playwright script:
// the pure classifier on page snapshots, and the requestInput relay driven
// by a scripted fake page. No Instagram account or browser is involved.

import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import test from "node:test";
import vm from "node:vm";

const root = join(dirname(new URL(import.meta.url).pathname), "..");
// The newest committed instagram-playwright source directory, so a new
// version is covered the moment its directory lands beside the tarball.
const VERSION = readdirSync(join(root, "artifacts/instagram-playwright"), { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && /^instagram-playwright-\d+\.\d+\.\d+$/.test(entry.name))
  .map((entry) => entry.name.replace("instagram-playwright-", ""))
  .sort((a, b) => { const [x, y] = [a, b].map((v) => v.split(".").map(Number)); return x[0] - y[0] || x[1] - y[1] || x[2] - y[2]; })
  .at(-1);
const script = readFileSync(
  join(root, `artifacts/instagram-playwright/instagram-playwright-${VERSION}/script.js`),
  "utf8",
);

const slice = (start, end) => {
  const startAt = script.indexOf(start);
  const endAt = script.indexOf(end, startAt);
  assert.notEqual(startAt, -1, `missing source starting with ${start}`);
  assert.notEqual(endAt, -1, `missing source ending with ${end}`);
  return script.slice(startAt, endAt);
};

// Loads the helpers between the error builders and the main flow against a
// fake page. checkLoginStatus is replaced so tests control login state.
const harness = (page, { loggedIn }) => {
  const source = [
    slice("const makeConnectorError =", "const inferErrorClass ="),
    slice("// ── Post-login challenge handling", "// Main export flow"),
    "globalThis.connector = { classifyChallenge, handlePostLoginChallenge };",
  ].join("\n");
  const context = vm.createContext({
    page,
    checkLoginStatus: async () => loggedIn(),
    console: { error: () => {} },
    Date,
  });
  vm.runInContext(source, context, { filename: "instagram-playwright-challenge.js" });
  return context.connector;
};

const snapshot = (overrides = {}) => ({
  path: "/challenge/123/abc/",
  bodyText: "",
  buttons: [],
  methodOptions: [],
  codeSelector: null,
  genericCodeSelector: null,
  hasLoginForm: false,
  ...overrides,
});

// A fake page whose evaluate returns the next snapshot when asked for one
// and records everything else. requestInput answers from a queue.
const scriptedPage = ({ snapshots, inputs = [] }) => {
  const calls = { requestInput: [], fill: [], click: [], status: [], evaluate: 0 };
  let snapIndex = 0;
  const page = {
    evaluate: async (source) => {
      calls.evaluate++;
      if (source.includes("methodOptions")) {
        const snap = snapshots[Math.min(snapIndex, snapshots.length - 1)];
        snapIndex++;
        return snap;
      }
      return true;
    },
    requestInput: async (spec) => {
      calls.requestInput.push(spec);
      assert.ok(inputs.length > 0, `unexpected requestInput: ${spec.message}`);
      return inputs.shift();
    },
    fill: async (selector, value) => { calls.fill.push({ selector, value }); },
    press: async () => {},
    click: async (selector) => { calls.click.push(selector); },
    sleep: async () => {},
    setData: async (key, value) => { if (key === "status") calls.status.push(value); },
  };
  return { page, calls };
};

const classify = (snap) =>
  harness({}, { loggedIn: () => false }).classifyChallenge(snap);

test("legacy two-factor input still reads as a code step", () => {
  const result = classify(snapshot({
    path: "/accounts/login/two_factor",
    codeSelector: 'input[name="verificationCode"]',
    bodyText: "enter the 6-digit code generated by your authentication app.",
    buttons: ["Confirm"],
  }));
  assert.equal(result.kind, "code");
  assert.equal(result.selector, 'input[name="verificationCode"]');
  assert.equal(result.channel, "your authentication app");
  assert.equal(result.submitButton, "Confirm");
});

test("a numeric input on a checkpoint URL reads as a code step", () => {
  const result = classify(snapshot({
    path: "/challenge/action/xyz/",
    genericCodeSelector: 'input[inputmode="numeric"]',
    bodyText: "enter the code we sent to j***@g****.com",
    buttons: ["Submit"],
  }));
  assert.equal(result.kind, "code");
  assert.equal(result.selector, 'input[inputmode="numeric"]');
  assert.equal(result.channel, "your email");
});

test("one-time-code autocomplete reads as a code step off the challenge path", () => {
  const result = classify(snapshot({
    path: "/auth_platform/codeentry/",
    codeSelector: 'input[autocomplete="one-time-code"]',
    bodyText: "check your text messages. enter the code we sent to +** *** ** 12",
  }));
  assert.equal(result.kind, "code");
  assert.equal(result.channel, "your phone");
});

test("a generic text input on the login page is not a code step", () => {
  const result = classify(snapshot({
    path: "/accounts/login/",
    genericCodeSelector: 'input[type="text"]',
    hasLoginForm: true,
    bodyText: "sorry, your password was incorrect.",
    buttons: ["Log in"],
  }));
  assert.equal(result.kind, "none");
});

test("choose-method page prefers email and names the send button", () => {
  const result = classify(snapshot({
    path: "/challenge/",
    bodyText: "help us confirm it's you. choose how you want to get a security code.",
    methodOptions: ["phone: +** *** ** 12", "email: j***@g****.com"],
    buttons: ["Send security code"],
  }));
  assert.equal(result.kind, "choose_method");
  assert.equal(result.option, "email: j***@g****.com");
  assert.equal(result.channel, "email");
  assert.equal(result.button, "Send security code");
});

test("choose-method page falls back to SMS when no email option exists", () => {
  const result = classify(snapshot({
    methodOptions: ["text message to +** *** ** 12"],
    buttons: ["Next"],
  }));
  assert.equal(result.kind, "choose_method");
  assert.equal(result.channel, "sms");
});

test("choose-method radios win over a generic text input", () => {
  const result = classify(snapshot({
    path: "/challenge/1/x/",
    bodyText: "choose how you want to get your security code",
    methodOptions: ["email m***@x.com", "sms +48 ***"],
    buttons: ["Send security code"],
    genericCodeSelector: 'input[type="text"]:not([name="username"]):not([name="email"])',
  }));
  assert.equal(result.kind, "choose_method");
  assert.equal(result.option, "email m***@x.com");
  assert.equal(result.button, "Send security code");
});

test("a named code input still wins over leftover radios", () => {
  const result = classify(snapshot({
    methodOptions: ["email m***@x.com"],
    buttons: ["Confirm"],
    codeSelector: 'input[name="security_code"]',
  }));
  assert.equal(result.kind, "code");
});

test("approve-on-another-device page reads as approve_elsewhere", () => {
  const result = classify(snapshot({
    path: "/auth_platform/",
    bodyText: "check your notifications on another device. approve the login request to continue.",
    buttons: ["Try another way"],
  }));
  assert.equal(result.kind, "approve_elsewhere");
});

test("'This was me' reads as affirm; bare Continue on a checkpoint reads as advance", () => {
  assert.deepEqual(
    { ...classify(snapshot({ path: "/", buttons: ["This Was Me", "This Wasn't Me"] })) },
    { kind: "affirm", button: "This Was Me" },
  );
  assert.deepEqual(
    { ...classify(snapshot({ path: "/checkpoint/", buttons: ["Continue"] })) },
    { kind: "advance", button: "Continue" },
  );
  assert.equal(classify(snapshot({ path: "/", buttons: ["Continue"] })).kind, "none");
});

test("choose method, then code: picks email, relays the code, logs in", async () => {
  let loggedIn = false;
  const { page, calls } = scriptedPage({
    snapshots: [
      snapshot({ methodOptions: ["email: j***@g****.com"], buttons: ["Send security code"] }),
      snapshot({
        genericCodeSelector: 'input[name="security_code"]',
        codeSelector: 'input[name="security_code"]',
        bodyText: "enter the code we sent to your email",
        buttons: ["Submit"],
      }),
    ],
    inputs: [{ code: "123 456" }],
  });
  const originalFill = page.fill;
  page.fill = async (selector, value) => { await originalFill(selector, value); loggedIn = true; };
  const { handlePostLoginChallenge } = harness(page, { loggedIn: () => loggedIn });
  const result = await handlePostLoginChallenge({ supportsRequestInput: true });
  assert.equal(result.loggedIn, true);
  assert.equal(calls.requestInput.length, 1);
  assert.match(calls.requestInput[0].message, /sent to your email/);
  assert.deepEqual(calls.fill, [{ selector: 'input[name="security_code"]', value: "123456" }]);
  assert.ok(calls.click.some((s) => s.includes("Send security code")));
  assert.ok(calls.click.some((s) => s.includes("Submit")));
  assert.ok(!calls.status.some((s) => s.includes("123")), "status must never carry the code");
});

test("a refused code is asked for once more, then fails as auth_failed", async () => {
  const codePage = snapshot({
    codeSelector: 'input[name="code"]',
    bodyText: "enter the 6-digit code",
  });
  const { page, calls } = scriptedPage({
    snapshots: [codePage],
    inputs: [{ code: "111111" }, { code: "222222" }],
  });
  const { handlePostLoginChallenge } = harness(page, { loggedIn: () => false });
  await assert.rejects(
    handlePostLoginChallenge({ supportsRequestInput: true }),
    (error) => error.telemetryError?.errorClass === "auth_failed" &&
      /did not accept the verification code/.test(error.message) &&
      !/111111|222222/.test(error.message),
  );
  assert.equal(calls.requestInput.length, 2);
  assert.match(calls.requestInput[1].message, /did not accept that code/);
});

test("approve elsewhere: notice via requestInput, then polls until logged in", async () => {
  let polls = 0;
  const { page, calls } = scriptedPage({
    snapshots: [snapshot({ bodyText: "waiting for approval. check your notifications on another device." })],
    inputs: [{ approved: true }],
  });
  const { handlePostLoginChallenge } = harness(page, {
    loggedIn: () => calls.requestInput.length > 0 && ++polls >= 3,
  });
  const result = await handlePostLoginChallenge({ supportsRequestInput: true });
  assert.equal(result.loggedIn, true);
  assert.equal(calls.requestInput.length, 1);
  assert.equal(calls.requestInput[0].schema.properties.approved.type, "boolean");
});

test("without requestInput a code step defers to the headed fallback", async () => {
  const { page, calls } = scriptedPage({
    snapshots: [snapshot({ codeSelector: 'input[name="verificationCode"]' })],
  });
  const { handlePostLoginChallenge } = harness(page, { loggedIn: () => false });
  const result = await handlePostLoginChallenge({ supportsRequestInput: false });
  assert.deepEqual({ ...result }, { loggedIn: false, reason: "verification code needed" });
  assert.equal(calls.requestInput.length, 0);
});

test("an unrecognized page returns without prompting", async () => {
  const { page, calls } = scriptedPage({
    snapshots: [snapshot({ path: "/accounts/login/", hasLoginForm: true })],
  });
  const { handlePostLoginChallenge } = harness(page, { loggedIn: () => false });
  const result = await handlePostLoginChallenge({ supportsRequestInput: true });
  assert.deepEqual({ ...result }, { loggedIn: false, reason: null });
  assert.equal(calls.requestInput.length, 0);
});

test("a non-numeric entry is re-asked as malformed, not as refused by Instagram", async () => {
  const { page, calls } = scriptedPage({
    snapshots: [snapshot({ codeSelector: 'input[name="code"]', bodyText: "enter the 6-digit code" })],
    inputs: [{ code: "abc" }, { code: "xyz" }],
  });
  const { handlePostLoginChallenge } = harness(page, { loggedIn: () => false });
  await assert.rejects(
    handlePostLoginChallenge({ supportsRequestInput: true }),
    (error) => error.telemetryError?.errorClass === "auth_failed" &&
      /not a 4-8 digit number/.test(error.message),
  );
  assert.equal(calls.requestInput.length, 2);
  assert.match(calls.requestInput[1].message, /doesn't look like a code\. Enter the digits only/);
  assert.doesNotMatch(calls.requestInput[1].message, /did not accept/);
  assert.equal(calls.fill.length, 0);
});

// Runs the whole script against a fake page: Instagram lands on a checkpoint
// with no login form, so the username/password prompt never appears.
const runWholeScript = ({ snapshots, inputs }) => {
  let loggedIn = false;
  let snapIndex = 0;
  const calls = { requestInput: [], fill: [], showBrowser: 0, data: {} };
  const page = {
    requestedScopes: () => ["instagram.profile"],
    goto: async () => {},
    sleep: async () => {},
    setData: async (key, value) => { calls.data[key] = value; },
    setProgress: async () => {},
    captureNetwork: async () => {},
    clearNetworkCaptures: async () => {},
    getCapturedResponse: async (key) =>
      key === "profileResponse"
        ? { data: { data: { user: { username: "someone", id: "1", following_count: 0 } } } }
        : null,
    waitForSelector: async () => { throw new Error("Timeout 10000ms exceeded"); },
    evaluate: async (source) => {
      if (source.includes("accounts/web_info")) {
        return loggedIn ? { success: true, data: { username: "someone" } } : { error: "no polaris data found" };
      }
      if (source.includes("methodOptions")) {
        return snapshots[Math.min(snapIndex++, snapshots.length - 1)];
      }
      return "none";
    },
    requestInput: async (spec) => {
      calls.requestInput.push(spec);
      assert.ok(inputs.length > 0, `unexpected requestInput: ${spec.message}`);
      return inputs.shift();
    },
    fill: async (selector, value) => { calls.fill.push({ selector, value }); loggedIn = true; },
    press: async () => {},
    click: async () => {},
    showBrowser: async () => { calls.showBrowser++; return { headed: false }; },
    promptUser: async () => { throw new Error("promptUser must not be reached"); },
    goHeadless: async () => {},
  };
  const context = vm.createContext({
    page,
    console: { error: () => {}, log: () => {} },
    setTimeout,
    clearTimeout,
    URLSearchParams,
  });
  const result = vm.runInContext(script, context, { filename: "instagram-playwright.js" });
  return { result, calls };
};

test("no login form: a direct checkpoint is relayed through requestInput", async () => {
  const { result, calls } = runWholeScript({
    snapshots: [snapshot({
      path: "/challenge/1/x/",
      codeSelector: 'input[name="security_code"]',
      bodyText: "enter the code we sent to m***@x.com",
      buttons: ["Confirm"],
    })],
    inputs: [{ code: "654321" }],
  });
  const output = await result;
  assert.equal(calls.requestInput.length, 1, "only the code prompt, no credentials prompt");
  assert.match(calls.requestInput[0].message, /verification code sent to your email/);
  assert.deepEqual(calls.fill, [{ selector: 'input[name="security_code"]', value: "654321" }]);
  assert.equal(calls.showBrowser, 0);
  assert.deepEqual([...output.errors], []);
  assert.equal(output["instagram.profile"].username, "someone");
});

test("no login form and no recognised checkpoint keeps the generic error", async () => {
  const { result, calls } = runWholeScript({
    snapshots: [snapshot({ path: "/", buttons: [] })],
    inputs: [],
  });
  const output = await result;
  assert.equal(calls.requestInput.length, 0);
  assert.equal(calls.showBrowser, 1);
  assert.equal(output.errors[0].errorClass, "auth_failed");
  assert.equal(output.errors[0].reason, "Instagram login requires a headed browser or requestInput support.");
});
